version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      action-deps:
        patterns:
          - "*"
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    groups:
      npm-deps:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
    cooldown:
      default-days: 7
