services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REPLICA_URL=s3://backup-bucket/auth-auth
      - DATABASE_URL=/app/auth.db
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin
      - AWS_ENDPOINT=http://rustfs:9000
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}

  rustfs:
    image: rustfs/rustfs:latest
    ports:
      - 9000:9000
    volumes:
      - s3_data:/data
    environment:
      - RUSTFS_ACCESS_KEY=admin
      - RUSTFS_SECRET_KEY=admin
      - RUSTFS_CONSOLE_ENABLE=true

volumes:
  s3_data:
